### ISSUE TITLE
English

### ISSUE THREAD

**Issue by TienIC** [beito123/Nukkit-Plugins-sub#1]
You should add English language

And compressed into file.jar

Anyway this is a great plugin, if the server uses canelrollback.jar

**Comment by TienIC** [comment]
Well, let me ask one more question. FixBihavior plugin, can it fix not display Him188's MyMap?

**Comment by beito123** [comment]
ok, I will add English file and release jar.

but, I think that it should not fix with FixBihavior.
so it should be fixed in a repo of the plugin.

**Comment by TienIC** [comment]
Okay, I got it. Thank you for your explanation
